// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Infrastructure.Persistence;

#nullable disable

namespace POS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260720111514_AddInventoryMovements")]
    partial class AddInventoryMovements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("POS.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_Name");

                    b.HasIndex("IsActive", "DisplayOrder", "Name")
                        .HasDatabaseName("IX_Categories_Active_DisplayOrder_Name");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_DisplayOrder_Range", "\"DisplayOrder\" >= 0 AND \"DisplayOrder\" <= 100000");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_InventoryMovements_OccurredAt");

                    b.HasIndex("MovementType", "OccurredAtUtc")
                        .HasDatabaseName("IX_InventoryMovements_Type_OccurredAt");

                    b.HasIndex("ProductId", "OccurredAtUtc")
                        .HasDatabaseName("IX_InventoryMovements_Product_OccurredAt");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("IX_InventoryMovements_Reference");

                    b.ToTable("InventoryMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryMovements_AdjustmentDirection", "\"MovementType\" <> 3 OR \"QuantityDelta\" <> 0");

                            t.HasCheckConstraint("CK_InventoryMovements_DecreaseDirection", "\"MovementType\" NOT IN (2, 5) OR \"QuantityDelta\" < 0");

                            t.HasCheckConstraint("CK_InventoryMovements_IncreaseDirection", "\"MovementType\" NOT IN (1, 6) OR \"QuantityDelta\" > 0");

                            t.HasCheckConstraint("CK_InventoryMovements_MovementType_Range", "\"MovementType\" >= 1 AND \"MovementType\" <= 7");

                            t.HasCheckConstraint("CK_InventoryMovements_OpeningBalance", "\"MovementType\" <> 7 OR (\"QuantityBefore\" = 0 AND \"QuantityDelta\" <> 0)");

                            t.HasCheckConstraint("CK_InventoryMovements_PerformedByUserId", "\"PerformedByUserId\" IS NULL OR \"PerformedByUserId\" > 0");

                            t.HasCheckConstraint("CK_InventoryMovements_ProductId_Positive", "\"ProductId\" > 0");

                            t.HasCheckConstraint("CK_InventoryMovements_QuantityAfter_Range", "\"QuantityAfter\" >= -999999999 AND \"QuantityAfter\" <= 999999999");

                            t.HasCheckConstraint("CK_InventoryMovements_QuantityBefore_Range", "\"QuantityBefore\" >= -999999999 AND \"QuantityBefore\" <= 999999999");

                            t.HasCheckConstraint("CK_InventoryMovements_QuantityDelta_Range", "\"QuantityDelta\" >= -1999999998 AND \"QuantityDelta\" <= 1999999998");

                            t.HasCheckConstraint("CK_InventoryMovements_QuantityEquation", "\"QuantityAfter\" = \"QuantityBefore\" + \"QuantityDelta\"");

                            t.HasCheckConstraint("CK_InventoryMovements_ReferencePair", "(\"ReferenceType\" IS NULL AND \"ReferenceId\" IS NULL) OR (\"ReferenceType\" IS NOT NULL AND \"ReferenceId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_InventoryMovements_ZeroDelta_StocktakeOnly", "\"QuantityDelta\" <> 0 OR \"MovementType\" = 4");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowNegativeStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CostPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("SalePrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Barcode")
                        .HasFilter("\"Barcode\" IS NOT NULL");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Code");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("CategoryId", "IsActive", "Name")
                        .HasDatabaseName("IX_Products_Category_Active_Name");

                    b.HasIndex("TrackInventory", "IsActive", "StockQuantity")
                        .HasDatabaseName("IX_Products_Inventory_Active_Stock");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_AllowNegativeStock_RequiresTracking", "\"AllowNegativeStock\" = 0 OR \"TrackInventory\" = 1");

                            t.HasCheckConstraint("CK_Products_CostPrice_Range", "\"CostPrice\" >= 0 AND \"CostPrice\" <= 999999999999");

                            t.HasCheckConstraint("CK_Products_MinimumStock_Range", "\"MinimumStock\" >= 0 AND \"MinimumStock\" <= 999999999");

                            t.HasCheckConstraint("CK_Products_MinimumStock_RequiresTracking", "\"TrackInventory\" = 1 OR \"MinimumStock\" = 0");

                            t.HasCheckConstraint("CK_Products_NegativeStock_Rule", "\"AllowNegativeStock\" = 1 OR \"StockQuantity\" >= 0");

                            t.HasCheckConstraint("CK_Products_SalePrice_Range", "\"SalePrice\" >= 0 AND \"SalePrice\" <= 999999999999");

                            t.HasCheckConstraint("CK_Products_StockQuantity_Range", "\"StockQuantity\" >= -999999999 AND \"StockQuantity\" <= 999999999");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("POS.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("POS.Domain.Entities.Product", b =>
                {
                    b.HasOne("POS.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("POS.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
