// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Infrastructure.Persistence;

#nullable disable

namespace POS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260721092716_AddOrdersPersistenceFoundation")]
    partial class AddOrdersPersistenceFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("POS.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_Name");

                    b.HasIndex("IsActive", "DisplayOrder", "Name")
                        .HasDatabaseName("IX_Categories_Active_DisplayOrder_Name");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_DisplayOrder_Range", "\"DisplayOrder\" >= 0 AND \"DisplayOrder\" <= 100000");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_InventoryMovements_OccurredAt");

                    b.HasIndex("MovementType", "OccurredAtUtc")
                        .HasDatabaseName("IX_InventoryMovements_Type_OccurredAt");

                    b.HasIndex("ProductId", "OccurredAtUtc")
                        .HasDatabaseName("IX_InventoryMovements_Product_OccurredAt");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("IX_InventoryMovements_Reference");

                    b.ToTable("InventoryMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryMovements_AdjustmentDirection", "\"MovementType\" <> 3 OR \"QuantityDelta\" <> 0");

                            t.HasCheckConstraint("CK_InventoryMovements_DecreaseDirection", "\"MovementType\" NOT IN (2, 5) OR \"QuantityDelta\" < 0");

                            t.HasCheckConstraint("CK_InventoryMovements_IncreaseDirection", "\"MovementType\" NOT IN (1, 6) OR \"QuantityDelta\" > 0");

                            t.HasCheckConstraint("CK_InventoryMovements_MovementType_Range", "\"MovementType\" >= 1 AND \"MovementType\" <= 7");

                            t.HasCheckConstraint("CK_InventoryMovements_OpeningBalance", "\"MovementType\" <> 7 OR (\"QuantityBefore\" = 0 AND \"QuantityDelta\" <> 0)");

                            t.HasCheckConstraint("CK_InventoryMovements_PerformedByUserId", "\"PerformedByUserId\" IS NULL OR \"PerformedByUserId\" > 0");

                            t.HasCheckConstraint("CK_InventoryMovements_ProductId_Positive", "\"ProductId\" > 0");

                            t.HasCheckConstraint("CK_InventoryMovements_QuantityAfter_Range", "\"QuantityAfter\" >= -999999999 AND \"QuantityAfter\" <= 999999999");

                            t.HasCheckConstraint("CK_InventoryMovements_QuantityBefore_Range", "\"QuantityBefore\" >= -999999999 AND \"QuantityBefore\" <= 999999999");

                            t.HasCheckConstraint("CK_InventoryMovements_QuantityDelta_Range", "\"QuantityDelta\" >= -1999999998 AND \"QuantityDelta\" <= 1999999998");

                            t.HasCheckConstraint("CK_InventoryMovements_QuantityEquation", "\"QuantityAfter\" = \"QuantityBefore\" + \"QuantityDelta\"");

                            t.HasCheckConstraint("CK_InventoryMovements_ReferencePair", "(\"ReferenceType\" IS NULL AND \"ReferenceId\" IS NULL) OR (\"ReferenceType\" IS NOT NULL AND \"ReferenceId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_InventoryMovements_ZeroDelta_StocktakeOnly", "\"QuantityDelta\" <> 0 OR \"MovementType\" = 4");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CancelledAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CashReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CashierUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChangeAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiscountAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long?>("PaidAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RefundedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestaurantTableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Subtotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_OrderCode");

                    b.HasIndex("CashierUserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Orders_Cashier_CreatedAtUtc");

                    b.HasIndex("CustomerId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Orders_Customer_CreatedAtUtc");

                    b.HasIndex("RestaurantTableId", "Status")
                        .HasDatabaseName("IX_Orders_Table_Status");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_Orders_Status_CreatedAtUtc");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_CancelledAtUtc_State", "(\"Status\" = 5 AND \"CancelledAtUtc\" IS NOT NULL) OR (\"Status\" <> 5 AND \"CancelledAtUtc\" IS NULL)");

                            t.HasCheckConstraint("CK_Orders_CashPayment_Rule", "\"PaymentMethod\" IS NULL OR \"PaymentMethod\" <> 1 OR \"CashReceived\" >= \"TotalAmount\"");

                            t.HasCheckConstraint("CK_Orders_CashReceived_NonNegative", "\"CashReceived\" >= 0");

                            t.HasCheckConstraint("CK_Orders_CashierUserId_Positive", "\"CashierUserId\" > 0");

                            t.HasCheckConstraint("CK_Orders_ChangeAmount_NonNegative", "\"ChangeAmount\" >= 0");

                            t.HasCheckConstraint("CK_Orders_ChangeNotAboveCash", "\"ChangeAmount\" <= \"CashReceived\"");

                            t.HasCheckConstraint("CK_Orders_CustomerId_Positive", "\"CustomerId\" IS NULL OR \"CustomerId\" > 0");

                            t.HasCheckConstraint("CK_Orders_DiscountAmount_Range", "\"DiscountAmount\" >= 0 AND \"DiscountAmount\" <= \"Subtotal\"");

                            t.HasCheckConstraint("CK_Orders_DiscountId_Positive", "\"DiscountId\" IS NULL OR \"DiscountId\" > 0");

                            t.HasCheckConstraint("CK_Orders_NonCashPayment_Rule", "\"PaymentMethod\" IS NULL OR \"PaymentMethod\" = 1 OR (\"CashReceived\" = 0 AND \"ChangeAmount\" = 0)");

                            t.HasCheckConstraint("CK_Orders_PaidAtUtc_State", "(\"Status\" IN (1, 2, 5) AND \"PaidAtUtc\" IS NULL) OR (\"Status\" IN (3, 4, 6, 7) AND \"PaidAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Orders_PaidState_Payment", "(\"Status\" IN (1, 2, 5) AND \"PaymentMethod\" IS NULL) OR (\"Status\" IN (3, 4, 6, 7) AND \"PaymentMethod\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Orders_PaymentMethod_Valid", "\"PaymentMethod\" IS NULL OR \"PaymentMethod\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Orders_RefundedAmount_Range", "\"RefundedAmount\" >= 0 AND \"RefundedAmount\" <= \"TotalAmount\"");

                            t.HasCheckConstraint("CK_Orders_RestaurantTableId_Positive", "\"RestaurantTableId\" IS NULL OR \"RestaurantTableId\" > 0");

                            t.HasCheckConstraint("CK_Orders_Status_Valid", "\"Status\" IN (1, 2, 3, 4, 5, 6, 7)");

                            t.HasCheckConstraint("CK_Orders_Subtotal_Range", "\"Subtotal\" >= 0 AND \"Subtotal\" <= 999999999999");

                            t.HasCheckConstraint("CK_Orders_TotalAmount_Equation", "\"TotalAmount\" = \"Subtotal\" - \"DiscountAmount\"");

                            t.HasCheckConstraint("CK_Orders_TotalAmount_Range", "\"TotalAmount\" >= 0 AND \"TotalAmount\" <= 999999999999");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LineDiscountAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefundedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitCostPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitSalePrice")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItems_OrderId");

                    b.HasIndex("ProductId", "CreatedAtUtc")
                        .HasDatabaseName("IX_OrderItems_Product_CreatedAtUtc");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_LineDiscount_NonNegative", "\"LineDiscountAmount\" >= 0");

                            t.HasCheckConstraint("CK_OrderItems_OrderId_Positive", "\"OrderId\" > 0");

                            t.HasCheckConstraint("CK_OrderItems_ProductId_Positive", "\"ProductId\" > 0");

                            t.HasCheckConstraint("CK_OrderItems_Quantity_Range", "\"Quantity\" > 0 AND \"Quantity\" <= 999999");

                            t.HasCheckConstraint("CK_OrderItems_RefundedQuantity_Range", "\"RefundedQuantity\" >= 0 AND \"RefundedQuantity\" <= \"Quantity\"");

                            t.HasCheckConstraint("CK_OrderItems_Status_Valid", "\"Status\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_OrderItems_UnitCostPrice_Range", "\"UnitCostPrice\" >= 0 AND \"UnitCostPrice\" <= 999999999999");

                            t.HasCheckConstraint("CK_OrderItems_UnitSalePrice_Range", "\"UnitSalePrice\" >= 0 AND \"UnitSalePrice\" <= 999999999999");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.OrderItemModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModifierGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifierGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitAdditionalPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId", "ModifierGroupId")
                        .HasDatabaseName("IX_OrderItemModifiers_Item_Group");

                    b.HasIndex("OrderItemId", "ModifierId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderItemModifiers_OrderItem_Modifier");

                    b.ToTable("OrderItemModifiers", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItemModifiers_GroupId_Positive", "\"ModifierGroupId\" > 0");

                            t.HasCheckConstraint("CK_OrderItemModifiers_ModifierId_Positive", "\"ModifierId\" > 0");

                            t.HasCheckConstraint("CK_OrderItemModifiers_OrderItemId_Positive", "\"OrderItemId\" > 0");

                            t.HasCheckConstraint("CK_OrderItemModifiers_Price_Range", "\"UnitAdditionalPrice\" >= 0 AND \"UnitAdditionalPrice\" <= 999999999");

                            t.HasCheckConstraint("CK_OrderItemModifiers_Quantity_Range", "\"Quantity\" > 0 AND \"Quantity\" <= 999999");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowNegativeStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CostPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("SalePrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Barcode")
                        .HasFilter("\"Barcode\" IS NOT NULL");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Code");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("CategoryId", "IsActive", "Name")
                        .HasDatabaseName("IX_Products_Category_Active_Name");

                    b.HasIndex("TrackInventory", "IsActive", "StockQuantity")
                        .HasDatabaseName("IX_Products_Inventory_Active_Stock");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_AllowNegativeStock_RequiresTracking", "\"AllowNegativeStock\" = 0 OR \"TrackInventory\" = 1");

                            t.HasCheckConstraint("CK_Products_CostPrice_Range", "\"CostPrice\" >= 0 AND \"CostPrice\" <= 999999999999");

                            t.HasCheckConstraint("CK_Products_MinimumStock_Range", "\"MinimumStock\" >= 0 AND \"MinimumStock\" <= 999999999");

                            t.HasCheckConstraint("CK_Products_MinimumStock_RequiresTracking", "\"TrackInventory\" = 1 OR \"MinimumStock\" = 0");

                            t.HasCheckConstraint("CK_Products_NegativeStock_Rule", "\"AllowNegativeStock\" = 1 OR \"StockQuantity\" >= 0");

                            t.HasCheckConstraint("CK_Products_SalePrice_Range", "\"SalePrice\" >= 0 AND \"SalePrice\" <= 999999999999");

                            t.HasCheckConstraint("CK_Products_StockQuantity_Range", "\"StockQuantity\" >= -999999999 AND \"StockQuantity\" <= 999999999");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockedUntilUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("LockedUntilUtc")
                        .HasDatabaseName("IX_Users_LockedUntilUtc");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedUsername");

                    b.HasIndex("IsActive", "Role", "FullName")
                        .HasDatabaseName("IX_Users_Active_Role_FullName");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_FailedLoginAttempts_NonNegative", "\"FailedLoginAttempts\" >= 0");

                            t.HasCheckConstraint("CK_Users_FullName_Length", "length(\"FullName\") >= 1 AND length(\"FullName\") <= 150");

                            t.HasCheckConstraint("CK_Users_NormalizedUsername_Length", "length(\"NormalizedUsername\") >= 3 AND length(\"NormalizedUsername\") <= 50");

                            t.HasCheckConstraint("CK_Users_PasswordHash_Length", "length(\"PasswordHash\") >= 1 AND length(\"PasswordHash\") <= 200");

                            t.HasCheckConstraint("CK_Users_Role_Valid", "\"Role\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Users_Username_Length", "length(\"Username\") >= 3 AND length(\"Username\") <= 50");
                        });
                });

            modelBuilder.Entity("POS.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("POS.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("POS.Domain.Entities.Order", b =>
                {
                    b.HasOne("POS.Domain.Entities.User", "CashierUser")
                        .WithMany()
                        .HasForeignKey("CashierUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashierUser");
                });

            modelBuilder.Entity("POS.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("POS.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("POS.Domain.Entities.OrderItemModifier", b =>
                {
                    b.HasOne("POS.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany("Modifiers")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("POS.Domain.Entities.Product", b =>
                {
                    b.HasOne("POS.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("POS.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("POS.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("POS.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
